---
###############################################################################
# Source Mod Install
###############################################################################
# Install source mod to target game installation.
#
# Simple admins configuration is only managed if sourcemod is enabled and
# admins are defined.
#
# Args:
#   steam_sourcemod_source: str source location of sourcemod tarball.
#   steam_sourcemod_game_dir: str target steamcmd game install location.
#   steam_sourcemod_admins: list [{user,priv}] of admins to manage.
#   steam_sourcemod_service: str service handler to trigger on updates.
#
# Reference:
# * https://wiki.alliedmods.net/Installing_SourceMod

- name: 'sourcemod | install'
  ansible.builtin.unarchive:
    src:     '{{ steam_sourcemod_source }}'
    dest:    '{{ steam_sourcemod_game_dir }}'
    owner:   '{{ steam_user }}'
    group:   '{{ steam_group }}'
    creates: '{{ steam_sourcemod_game_dir }}/addons/sourcemod/bin'
  when: steam_sourcemod_source|length > 0
  notify: 'restart {{ steam_sourcemod_service }}'

- name: 'sourcemod | set simple admins'
  ansible.builtin.template:
    src:   'sourcemod/admins_simple.ini.j2'
    dest:  '{{ steam_sourcemod_game_dir }}/addons/sourcemod/configs/admins_simple.ini'
    owner: '{{ steam_user }}'
    group: '{{ steam_group }}'
    mode:  0600
  when: steam_sourcemod_source|length > 0 and steam_sourcemod_admins|length > 0
  notify: 'restart {{ steam_sourcemod_service }}'
