---
###############################################################################
# Steam Core
###############################################################################
# Caculate core steam variables for installation and upgrade.
#
# Winetricks latest releases may be unverified, so always search for the latest
# verified release. These releases will have assets attached to them --
# unverified releases will not.
#
# Generates:
#   _steam_winetricks_url: string URL to download winetricks release.
#   _steam_winetricks_latest: string latest verified winetricks version.
#   _steam_client_sdk32_generic: str path to generic sdk32.
#   _steam_client_sdk64_generic: str path to generic sdk64.
#   _steam_client_sdk32_share: str path to shared sdk32.
#   _steam_client_sdk64_share: str path to shared sdk64.
#   _steam_wine_enable: bool true if wine must be installed.

- name: 'core | setup winetricks metadata'
  ansible.builtin.set_fact:
    _winetricks_github_latest_metadata: ''

- name: 'core | get winetricks release metadata'
  ansible.builtin.uri:
    url: 'https://api.github.com/repos/Winetricks/winetricks/releases'
    return_content: true
  register: _steam_github_winetricks

- name: 'core | find latest verified winetricks release'
  ansible.builtin.set_fact:
    _winetricks_github_latest_metadata: '{{ item if item.assets|length > 0 else "" }}'
  loop: '{{ _steam_github_winetricks.json }}'
  when: _winetricks_github_latest_metadata|length == 0

- name: 'core | set latest winetricks release'
  ansible.builtin.set_fact:
    _steam_winetricks_latest: '{{ _winetricks_github_latest_metadata.tag_name }}'
    _steam_wine_enable:       false

- name: 'core | determine if wine should be installed'
  ansible.builtin.set_fact:
    _steam_wine_enable: true
  when: >
    steam_wine_enable or
    steam_conan_enable

- name: 'core | generate install configuration'
  ansible.builtin.set_fact:
    _steam_winetricks_url:       'https://github.com/Winetricks/winetricks/archive/refs/tags/{{ _steam_winetricks_latest }}.tar.gz'
    _steam_client_sdk32_generic: '/home/{{ steam_user }}/.steam/sdk32/steamclient.so'
    _steam_client_sdk64_generic: '/home/{{ steam_user }}/.steam/sdk64/steamclient.so'
    _steam_client_sdk32_share:   '/home/{{ steam_user }}/.local/share/Steam/steamcmd/linux32/steamclient.so'
    _steam_client_sdk64_share:   '/home/{{ steam_user }}/.local/share/Steam/steamcmd/linux64/steamclient.so'
