---
###############################################################################
# Install Steamcmd
###############################################################################
# Install steamcmd base.
#
# Reference:
# * https://developer.valvesoftware.com/wiki/SteamCMD#Linux

- name: 'Install | enable i386 architecture support'
  ansible.builtin.command: 'dpkg --add-architecture i386'
  args:
    creates: '/var/lib/dpkg/arch'

- name: 'Install | packages'
  ansible.builtin.include_role:
    name: 'r_pufky.deb.apt'
  vars:
    apt_packages:
      - '{{ steam_role_packages }}'
    apt_sources: '{{
        steam_role_apt_sources
        if _steam_srv_auto_add_apt_sources_enable.raw else
        []
      }}'
    apt_package_update_cache: true

- name: 'Install | updating steamcmd 🗘'
  ansible.builtin.debug:
    msg: |
      ╭───────────────────────────────────────────────────────────────────╮
      │                                                                   │
      │     steamcmd is being updated. This will take a few minutes.      │
      │                                                                   │
      ╰───────────────────────────────────────────────────────────────────╯

- name: 'Install | update steamcmd'
  ansible.builtin.shell: >-
    /usr/games/steamcmd
    +login anonymous
    +quit
  args:
    executable: '/bin/bash'
    chdir: '{{ _steam_srv_user.role_home }}'
  changed_when: false
  become: true
  become_user: '{{ _steam_srv_user.raw }}'
