---
###############################################################################
# Steamcmd Install
###############################################################################
# Install steamcmd base. Enabling wine installs XVFB window manager and latest
# winetricks.
#
# Reference:
# * https://developer.valvesoftware.com/wiki/SteamCMD#Linux
# * https://wiki.winehq.org/Debian
# * https://wiki.winehq.org/Winetricks

- name: 'Install | enable i386 architecture support'
  ansible.builtin.command: 'dpkg --add-architecture i386'
  args:
    creates: '/var/lib/dpkg/arch'

- name: 'Install | packages'
  ansible.builtin.include_role:
    name: 'r_pufky.deb.apt'
  vars:
    apt_packages:
      - '{{ steam_role_packages_x64 }}'
      - '{{ steam_role_packages_i386 }}'
      - '{{ steam_role_wine_packages_x64 }}'
      - '{{ steam_role_wine_packages_i386 }}'
    apt_sources: '{{
        steam_role_apt_sources
        if steam_srv_auto_add_apt_sources_enable else
        []
      }}'
    apt_package_update_cache: true

- name: 'Install | updating steamcmd 🗘'
  ansible.builtin.debug:
    msg: |
      ╭───────────────────────────────────────────────────────────────────╮
      │                                                                   │
      │     steamcmd is being updated. This will take a few minutes.      │
      │                                                                   │
      ╰───────────────────────────────────────────────────────────────────╯

- name: 'Install | update steamcmd'
  ansible.builtin.shell: '/usr/games/steamcmd +quit'
  args:
    executable: '/bin/bash'
    chdir: '{{ _steam_srv_user.role_home }}'
  changed_when: false
  become: true
  become_user: '{{ _steam_srv_user.raw }}'

- name: 'Install | wine'
  when: _steam_srv_wine_enable.raw
  block:

    - name: 'Install | wine | {{ _steam_srv_wine_release.raw }}'
      ansible.builtin.apt:
        name: 'winehq-{{ _steam_srv_wine_release.raw }}'
        state: 'present'
        install_recommends: true

    - name: 'Install | wine | updating wine 🗘'
      ansible.builtin.debug:
        msg: |
          ╭───────────────────────────────────────────────────────────────────╮
          │                                                                   │
          │         wine being updated. This will take a few minutes.         │
          │                                                                   │
          ╰───────────────────────────────────────────────────────────────────╯

    - name: 'Install | wine | update wine'
      ansible.builtin.command: '/usr/bin/wineboot --update'
      args:
        chdir: '{{ _steam_srv_user.role_home }}'
      changed_when: false
      become: true
      become_user: '{{ _steam_srv_user.raw }}'

    - name: 'Install | wine | update winetricks'
      ansible.builtin.include_role:
        name: 'r_pufky.deb.repo'
      vars:
        repo_release_owner: '{{ steam_role_repo_release_owner }}'
        repo_release_repo: '{{ steam_role_repo_release_repo }}'
        repo_release_tag: '{{ _steam_srv_winetricks_release.raw }}'
        repo_release_download_source_enable: true
        repo_release_asset: '{{ steam_role_repo_release_asset }}'
        repo_release_gpg_key_id: '{{ steam_role_repo_release_gpg_key_id }}'
        repo_extract_dir: '{{ steam_role_repo_extract_dir }}'
        repo_extract_symlink: '{{ steam_role_repo_extract_symlink }}'
        repo_extract_mode: 'a-st,o-rwx'
        repo_extract_extra_opts: '--strip-components=1'

    - name: 'Install | wine | install winetricks'
      when: _repo_changed
      ansible.builtin.copy:
        remote_src: true
        src: '{{ steam_role_repo_extract_symlink ~ "/src/winetricks"}}'
        dest: '/usr/local/bin/winetricks'
        owner: 'root'
        group: 'root'
        mode: '0755'
        directory_mode: '0755'
        force: true
