---
- name: 'Annotate'
  ansible.builtin.include_tasks: 'annotate.yml'
- name: 'Prep'
  ansible.builtin.include_tasks: 'prep.yml'
- name: 'Install steamcmd'
  ansible.builtin.include_tasks: 'install_steamcmd.yml'

- name: 'Install wine'
  when: _steam_srv_wine_enable.raw
  ansible.builtin.include_tasks: 'install_wine.yml'
