---
###############################################################################
# Steam Tasks
###############################################################################
# Developer Notes:
# Use game names for directory and unique file names (excluding main) within:
# duplicate file names in a role will lead to nondeterministic behavior.

- ansible.builtin.include_tasks: manage_users.yml
- ansible.builtin.include_tasks: core.yml
- ansible.builtin.include_tasks: steamcmd/main.yml
- ansible.builtin.include_tasks: wine/main.yml
