---
###############################################################################
# Metamod
###############################################################################
# Reference:
# * https: //www.sourcemm.net/downloads.php?branch=stable

- name: 'Metamod | filesystem | set system directories'
  ansible.builtin.file:
    path: '{{ steam__mm._src_dir }}'  # src_dir includes opt_dir.
    owner: 'root'
    group: 'root'
    mode: '0755'
    state: 'directory'

- name: 'Metamod | filesystem | find previous installations'
  ansible.builtin.find:
    paths: '{{ steam__mm._src_dir }}'
    file_type: 'file'
    recurse: false
    excludes:
      - '{{ steam__mm._package }}'
  register: steam__cmd

- name: 'Metamod | filesystem | remove previous installations'
  ansible.builtin.file:
    path: '{{ item.path }}'
    state: 'absent'
  loop: '{{ steam__cmd.files }}'
  loop_control:
    label: '{{ item.path }}'

- name: 'Metamod | url | 🗘 metamod (~1 minute) 🗘'
  when: not (url_inject_enable | default(false))
  ansible.builtin.get_url:
    url: '{{ steam__mm._url }}'
    dest: '{{ "/tmp/" ~ steam__mm._package }}'
    force: false
    owner: 'root'
    group: 'root'
    mode: '0644'
  register: steam__cmd
  until: steam__cmd is succeeded

- name: '{{ "Metamod | filesystem | stage " ~ steam__mm._package }}'
  ansible.builtin.copy:
    remote_src: true
    src: '{{ "/tmp/" ~ steam__mm._package }}'
    dest: '{{ steam__mm._dest }}'
    owner: 'root'
    group: 'root'
    mode: '0644'
