---
###############################################################################
# Update SteamCMD.
###############################################################################
#
# Args:
#   steam_platform: str - Platform install type.
#       Values:
#           linux: Linux based game (default).
#         windows: Windows based game.
#       Default: 'linux'.

- name: 'Steamcmd | updating steamcmd 🗘'
  ansible.builtin.debug:
    msg: |
      ╭───────────────────────────────────────────────────────────────────╮
      │                                                                   │
      │      Steamcmd is being updated. This may take a few minutes.      │
      │                                                                   │
      ╰───────────────────────────────────────────────────────────────────╯

- name: 'Steamcmd | update steamcmd'
  ansible.builtin.shell: >-
    /usr/games/steamcmd
    +@sSteamCmdForcePlatformType
      {{ steam_platform | default('linux') | lower }}
    +login anonymous
    +quit
  args:
    executable: '/bin/bash'
    chdir: '{{ _steam_srv_user.role_home }}'
  changed_when: false
  become: true
  become_user: '{{ _steam_srv_user.raw }}'
