---
###############################################################################
# Update/Install Specific Server via SteamCMD.
###############################################################################
# Set force_install_dir before logging in.
#
# Args:
#   steam_app_id: int - Application ID.
#   steam_platform: str - Platform install type.
#       Values:
#           linux: Linux based game (default).
#         windows: Windows based game.
#       Default: 'linux'.
#   steam_dir: str - Application working directory.
#       Default: '{{ _steam_srv_user.role_home }}'.
#   steam_app_extras: str - Extra install options.
#       Default: ''.
#   steam_app_beta: str - Beta version options.
#       Default: ''.
#
# Reference:
# * https://github.com/ValveSoftware/steam-for-linux/issues/8298

- name: 'Steamcmd | updating server 🗘'
  ansible.builtin.debug:
    msg: |
      ╭───────────────────────────────────────────────────────────────────╮
      │                                                                   │
      │       Server is being updated. This may take a few minutes.       │
      │                                                                   │
      ╰───────────────────────────────────────────────────────────────────╯

# TODO: indentations on shell line cause steamcmd errror --see seven.
- name: 'Steamcmd | update server {{ steam_app_id }}'
  ansible.builtin.shell: >-
    /usr/games/steamcmd
    +@sSteamCmdForcePlatformType
      {{ steam_platform | default('linux') | lower }}
    +force_install_dir {{ steam_dir | default(_steam_srv_user.role_home) }}
    +login anonymous
    +app_update
      {{ steam_app_id }}
      {{ steam_app_extras | default("") }}
      {{ steam_app_beta | default("") }}
    +quit
  args:
    executable: '/bin/bash'
    chdir: '{{ _steam_srv_user.role_home }}'
  changed_when: false
  become: true
  become_user: '{{ _steam_srv_user.raw }}'
