---
###############################################################################
# Left 4 Dead Install
###############################################################################
# Install location is relative to base installation directory. This is **not**
# customizable, contary to many mis-documented Internet configurations.
#
# server.cfg must be located in left4dead/cfg and can only be referenced on
# start using the relative path from that location (server.cfg).
#
# Generates:
#   _steam_l4d_dir: str install location of l4d.
#
# Reference:
# * https://github.com/r-pufky/steam/blob/master/docs/examples/left-4-dead.md

- name: 'l4d | generate install configuration'
  ansible.builtin.set_fact:
    _steam_l4d_dir: '{{ steam_l4d_dir }}/left4dead'
    _steam_l4d_systemd:
      description:       'L4D Dedicated Server'
      after:             'network.target'
      user:              '{{ steam_user }}'
      group:             '{{ steam_group }}'
      working_directory: '{{ steam_l4d_dir }}'
      environment:
        - 'LD_LIBRARY_PATH={{ steam_l4d_dir }}:{{ steam_l4d_dir }}/bin'
      exec_start_pre:    '/usr/games/steamcmd +@sSteamCmdForcePlatformType {{ steam_default_l4d_platform }} +force_install_dir {{ steam_l4d_dir }} +login anonymous +app_update {{ steam_default_l4d_app_id }} {{ steam_l4d_app_extras }} +quit'
      exec_start:        '{{ steam_l4d_dir }}/srcds_run -console -game left4dead -map l4d_hospital01_apart -port 27015 +maxplayers 4 -nohltv +exec server.cfg -pidfile /tmp/l4d.pid'
      timeout_start_sec: 'infinity'
      restart:           'always'
      limit_no_file:     4096
      wanted_by:         'multi-user.target'

- name: 'l4d | create server directory'
  ansible.builtin.file:
    path:  '{{ steam_l4d_dir }}'
    owner: '{{ steam_user }}'
    group: '{{ steam_group }}'
    mode:  0755
    state: 'directory'

- ansible.builtin.import_tasks: roles/steam/tasks/update_steam.yml
  vars:
    steam_platform: '{{ steam_default_l4d_platform }}'
  when: steam_l4d_update_steamcmd

- ansible.builtin.import_tasks: roles/steam/tasks/update_server.yml
  vars:
    steam_platform:   '{{ steam_l4d_platform }}'
    steam_dir:        '{{ steam_l4d_dir }}'
    steam_app_id:     '{{ steam_default_l4d_app_id }}'
    steam_app_extras: '{{ steam_l4d_app_extras }}'
  when: steam_l4d_update_server

- name: 'l4d | set server config'
  ansible.builtin.template:
    src:   'server.cfg.j2'
    dest:  '{{ _steam_l4d_dir }}/cfg/server.cfg'
    owner: '{{ steam_user }}'
    group: '{{ steam_group }}'
    mode:  0600
  vars:
    server: '{{ steam_l4d_server }}'
  notify: 'restart l4d.service'

- name: 'l4d | create service'
  ansible.builtin.template:
    src:   'systemd.service.j2'
    dest:  '/etc/systemd/system/l4d.service'
    owner: 'root'
    group: 'root'
    mode:  0755
  vars:
    systemd: '{{ steam_l4d_systemd }}'
  notify: 'restart l4d.service'

- name: 'l4d | set motd'
  ansible.builtin.copy:
    dest:    '{{ _steam_l4d_dir }}/motd.txt'
    owner:   '{{ steam_user }}'
    group:   '{{ steam_group }}'
    mode:    0600
    content: '{{ steam_l4d_motd }}'
  notify: 'restart l4d.service'

- name: 'l4d | set host'
  ansible.builtin.copy:
    dest:    '{{ _steam_l4d_dir }}/host.txt'
    owner:   '{{ steam_user }}'
    group:   '{{ steam_group }}'
    mode:    0600
    content: '{{ steam_l4d_host }}'
  notify: 'restart l4d.service'
