---
###############################################################################
# Install Winetricks
###############################################################################
# Latest winetricks patches always applied.
#
# Args:
#   _steam_winetricks_url: string URL to download winetricks release.
#   _steam_winetricks_latest: string latest verified winetricks version.
#
# Reference:
# * https://wiki.winehq.org/Winetricks

- name: 'winetricks | determine installed winetricks version'
  ansible.builtin.command: '/usr/local/bin/winetricks --version'
  changed_when: false
  failed_when: false
  register: _winetricks_local

- name: 'winetricks | set local winetricks release'
  ansible.builtin.set_fact:
    _winetricks_local_release: "{{ _winetricks_local.stdout.split('-')[0]|trim }}"
  when: _winetricks_local.rc == 0

- name: 'winetricks | install/update winetricks'
  ansible.builtin.unarchive:
    src:   '{{ _steam_winetricks_url }}'
    remote_src: true
    dest:  '/usr/local/bin'
    owner: 'root'
    group: 'root'
    mode:  0755
    extra_opts:
      - '--strip=2'
      - '--no-anchored'
      - 'winetricks'
  when: >
    _winetricks_local.rc != 0 or
    _winetricks_local_release != _steam_winetricks_latest
