---
###############################################################################
# Conan Exiles Mods Install
###############################################################################
# Install Conan Exiles Mods
#
# Args:
#   _steam_conan_mods_dir: str mods install location.
#
# Reference:
# * https://r-pufky.github.io/docs/game/conan/setup.html
# * https://github.com/r-pufky/steam/blob/master/docs/examples/conan-exiles.md

- name: 'conan | install mods'
  ansible.builtin.copy:
    src:   '{{ steam_conan_mods_source if steam_conan_mods_source[-1] == "/" else steam_conan_mods_source+"/" }}'
    dest:  '{{ _steam_conan_mods_dir }}'
    owner: '{{ steam_user }}'
    group: '{{ steam_group }}'
    mode:  0700
  when: steam_conan_mods_source
  notify: 'restart conan.service'

- name: 'conan | install modlist.txt'
  ansible.builtin.template:
    src:   'conan_exiles/modlist.txt.j2'
    dest:  '{{ _steam_conan_mods_dir }}/modlist.txt'
    owner: '{{ steam_user }}'
    group: '{{ steam_group }}'
    mode:  0600
  when: steam_conan_mods|length > 0
  notify: 'restart conan.service'
