---
###############################################################################
# Wine
###############################################################################
# Wine is installed and usable by steam user with no errors.
#
# Tests:
# * steamcmd works correctly.
# * Wine packages installed correctly.

dependency:
  name: 'galaxy'
driver:
  name: 'podman'
provisioner:
  name: 'ansible'
  config_options:
    defaults:
      interpreter_python: 'auto_silent'
      callback_whitelist: 'profile_tasks, timer, yaml'
    ssh_connection:
      pipelining: false
  inventory:
    host_vars:
      steam-debian-13-wine:
        steam_srv_wine_enable: true
        steam_srv_wine_raw_network_enable: true
platforms:
  - name: 'steam-debian-13-wine'
    image: 'ghcr.io/hifis-net/debian-systemd:13'
    systemd: 'always'
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    command: '/lib/systemd/systemd'
    pre_build_image: true
verifier:
  name: 'ansible'
lint: |
  set -e
  yamllint .
  ansible-lint .
scenario:
  test_sequence:
    # - 'dependency'
    # - 'cleanup'
    - 'destroy'
    - 'syntax'
    - 'create'
    - 'prepare'
    - 'converge'
    # - 'idempotence'  # services always restarted.
    # - 'side_effect'
    - 'verify'
    # - 'cleanup'
    - 'destroy'
