---
###############################################################################
# Default
###############################################################################
# Default values results in usable steamcmd.
#
# Steamcmd is installed and usable by steam user with no errors.
#
# Tests:
# * /srv/backup created with correct permissions.
# * steam_srv_user_data_manage_enable directories created.
# * steamcmd works correctly.

dependency:
  name: 'galaxy'
driver:
  name: 'vagrant'
  provider:
    name: 'libvirt'
    type: 'libvirt'
provisioner:
  name: 'ansible'
  connection_options:
    ansible_ssh_user: 'vagrant'
    ansible_become: true
  config_options:
    defaults:
      interpreter_python: 'auto_silent'
      callback_whitelist: 'profile_tasks, timer, yaml'
  inventory:
    group_vars:
      all:
        molecule_flg_inject: true
        steam_flg_cdn: true
        steam_flg_wine: true
        steam_flg_metamod: true
        steam_flg_sourcemod: true
        steam_srv_raw_network: true
        steam_flg_update: false
platforms:
  - name: 'steam-default'
    box: 'debian/trixie64'
    memory: 4096
    cpus: 2
    interfaces:
      - network_name: 'private_network'
        auto_config: true
        type: 'dhcp'
verifier:
  name: 'ansible'
scenario:
  test_sequence:
    - 'destroy'
    - 'syntax'
    - 'create'
    - 'prepare'
    - 'converge'
    - 'verify'
    - 'destroy'
