---
###############################################################################
# Install SteamCMD
###############################################################################
# Install steamcmd base.
#
# A generic steamclient.so is linked sourced from .local/share. This prevents
# an alarming but harmless error in the logs. Most games ship with a specific
# steamclient.so in their installs, and those are preferred over the steamcmd
# client.
#
# Args:
#   _steam_client_sdk32_generic: str path to generic sdk32.
#   _steam_client_sdk64_generic: str path to generic sdk64.
#   _steam_client_sdk32_share: str path to shared sdk32.
#   _steam_client_sdk64_share: str path to shared sdk64.
#
# Reference:
# * https://developer.valvesoftware.com/wiki/SteamCMD#Linux

- name: 'install steam | enable i386 architecture support'
  ansible.builtin.command: 'dpkg --add-architecture i386'
  args:
    creates: '/var/lib/dpkg/arch'

- name: 'install steam | update apt cache'
  ansible.builtin.apt:
    update_cache: true

- name: 'install steam | preconfigure steam license viewed'
  ansible.builtin.debconf:
    name:     'steam'
    question: 'steam/license'
    value:    "note ''"
    vtype:    'string'

- name: 'install steam | preconfigure steam license agreement'
  ansible.builtin.debconf:
    name:     'steam'
    question: 'steam/question'
    value:    'I AGREE'
    vtype:    'select'

- name: 'install steam | install core packages'
  ansible.builtin.apt:
    name:  '{{ steam_default_core_packages }}'
    state: 'latest'
    install_recommends: true

- name: 'install steam | install i386 specific packages'
  ansible.builtin.apt:
    name:  '{{ steam_default_i386_packages }}'
    state: 'latest'
    install_recommends: true
  when: steam_default_i386_packages|length > 0

- name: 'install steam | run steamcmd to update' # noqa no-changed-when always execute
  ansible.builtin.command: '/usr/games/steamcmd +quit'
  args:
    chdir: '/home/steam'
  become_user: '{{ steam_user }}'
  # Reference: https://github.com/ansible/ansible/issues/16048#issuecomment-229012509
  vars:
    ansible_ssh_pipelining: true

- name: 'install steam | ensure sdk directories exist'
  ansible.builtin.file:
    name:  '{{ item }}'
    owner: '{{ steam_user }}'
    group: '{{ steam_group }}'
    mode:  0700
    state: 'directory'
  loop:
    - '{{ _steam_client_sdk32_generic|dirname }}'
    - '{{ _steam_client_sdk64_generic|dirname }}'

- name: 'install steam | link base steamclient binaries to shared'
  ansible.builtin.file:
    src:   '{{ item.share }}'
    dest:  '{{ item.generic }}'
    owner: '{{ steam_user }}'
    group: '{{ steam_group }}'
    mode:  0750
    state: 'hard'
    force: true
  changed_when: false
  loop:
    - {generic: '{{ _steam_client_sdk32_generic }}', share: '{{ _steam_client_sdk32_share }}'}
    - {generic: '{{ _steam_client_sdk64_generic }}', share: '{{ _steam_client_sdk64_share }}'}
