---
###############################################################################
# Update/Install Specific Server via SteamCMD
###############################################################################
#
# Args:
#   steam_app_id: integer application id to install.
#   steam_platform: string platform install type (linux, windows).
#   steam_dir: string application working directory.
#   steam_app_extras: string extra install options.
#   steam_app_beta: string beta version options.

- name: 'update server | (may take a while)'
  ansible.builtin.debug:
    msg: |
      Server is being updated. This may take a few minutes.

# Set force_install_dir before logging in.
# Reference:
# * https://github.com/ValveSoftware/steam-for-linux/issues/8298
- name: 'update server | {{ _app_id }}' # noqa no-changed-when always execute
  ansible.builtin.command: '/usr/games/steamcmd +@sSteamCmdForcePlatformType {{ _platform }} +force_install_dir {{ _dir }} +login anonymous +app_update {{ _app_id }} {{ _app_extras }} {{ _app_beta }} +quit'
  args:
    chdir: '/home/{{ steam_user }}'
  become_user: '{{ steam_user }}'
  # Reference: https://github.com/ansible/ansible/issues/16048#issuecomment-229012509
  vars:
    ansible_ssh_pipelining: true
    _platform:   '{{ steam_platform }}'
    _dir:        '{{ steam_dir }}'
    _app_id:     '{{ steam_app_id }}'
    _app_extras: '{{ steam_app_extras }}'
    _app_beta:   '{{ steam_app_beta }}'
